service: reto-star-wars-api

frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-jetpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 20

resources:
  Resources:
    testTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: testTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  api:
    handler: src/lambda.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}
